{
 "title": "Tier 2 / Application Gateway",
 "description": "Use Azure Monitor to view  Application Gateways",
 "tags": [
  "cwhd",
  "source:grafana-labs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ResourceName",
    "label": "App Gateway",
    "query": {}
   },
   {
    "name": "law_sub",
    "label": "Workspace Subscription",
    "query": {}
   },
   {
    "name": "law_rg",
    "label": "Workspace RG",
    "query": {}
   },
   {
    "name": "law",
    "label": "Workspace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "App Gateway Total Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "ApplicationGatewayTotalTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Healthy Backend Host Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "New connections per second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "NewConnectionsPerSecond",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "ResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Failed Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Unhealthy Backend Host Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "CurrentConnections",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Backend Connect Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BackendConnectTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Backend First Byte Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BackendFirstByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Backend Last Byte Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Est. Billed Capacity Units",
   "type": "timeseries",
   "description": "Estimated billed capacity units",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "EstimatedBilledCapacityUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Backend Response Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BackendResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Backend Last Byte Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Current Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "CapacityUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Fixed Billed Capacity Units",
   "type": "timeseries",
   "description": "Estimated billed capacity units",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "FixedBillableCapacityUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Current Compute Units",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "ComputeUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Client TLS Protocol",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "TlsProtocol",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Client RTT",
   "type": "timeseries",
   "description": "Client round trip time",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.network/applicationgateways",
      "metricName": "ClientRtt",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "southeastasia",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscriptions"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "### Access & WAF Logs\r\n<hr style=\"height: 1px; background-color: #FFFFFF\">"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 7, "x": 15, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Access Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "AGWAccessLogs \n| where TimeGenerated >= ago(30d)\n| extend ReceivedBytesMB = ReceivedBytes / 1000\n| extend SentBytesdMB = SentBytes / 1000\n| extend RequestUrl = strcat(HttpMethod, ' ', OriginalHost, OriginalRequestUriWithArgs)\n| extend RouteFlow = strcat(ClientIp, ' -> ', RequestUrl, ' -> ', ServerRouted )\n| extend DatetimeSG = datetime_utc_to_local(TimeGenerated, 'Asia/Singapore')\n| project \n    DatetimeSG,\n    ['TimeTakenSec'] = TimeTaken,\n    ReceivedBytesMB, \n    SentBytesdMB,\n    SslEnabled,\n    RouteFlow,\n    ['Backend Status']=ServerStatus,\n    ['Backend Resp Latency (Sec)'] = ServerResponseLatency\n| summarize \n    ['Max Data Received MB']=max(ReceivedBytesMB), \n    ['Max Data Returned MB']=max(SentBytesdMB), \n    ['Max Time Taken (Sec)']=max(TimeTakenSec) by \n    RouteFlow, \n    ['Backend Status'], \n    SslEnabled",
      "resources": [
       "/subscriptions/$law_sub/resourceGroups/$law_rg/providers/Microsoft.OperationalInsights/workspaces/$law"
      ],
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "All WAF Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "AGWFirewallLogs \n| where TimeGenerated >= $__timeFrom()\n| project \n['Datetime SG'] = datetime_local_to_utc(TimeGenerated, 'Asia/Singapore'), \nClientIp,\nAction,\nUrl=strcat(Hostname,RequestUri), \nMessage=strcat(Message, '\\n', DetailedMessage, '\\n', FileDetails), FileDetails",
      "resources": [
       "/subscriptions/$law_sub/resourceGroups/$law_rg/providers/Microsoft.OperationalInsights/workspaces/$law"
      ],
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "WAF Blocked List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "AGWFirewallLogs \n| where Action == \"Blocked\"\n| where TimeGenerated >= $__timeFrom\n| project \n['Datetime SG'] = datetime_local_to_utc(TimeGenerated, 'Asia/Singapore'), \nClientIp, \nUrl=strcat(Hostname,RequestUri), \nMessage=strcat(Message, '\\n', DetailedMessage, '\\n', FileDetails), FileDetails",
      "resources": [
       "/subscriptions/$law_sub/resourceGroups/$law_rg/providers/Microsoft.OperationalInsights/workspaces/$law"
      ],
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  }
 ]
}