{
 "title": "Tier 2 / API Management",
 "description": "Dashboard for API Management service. Monitors health, API, operations, and requests. Contains panels which utilize App Insights and Log Analytics (if enabled).",
 "tags": [
  "cwhd",
  "source:grafana-labs"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   { "name": "ns_appinsights", "query": "${VAR_NS_APPINSIGHTS}" },
   { "name": "ns_logs", "query": "${VAR_NS_LOGS}" },
   {
    "name": "resource_apim",
    "label": "API Management service",
    "query": {}
   },
   { "name": "ns_apim", "label": "Namespace", "query": "${VAR_NS_APIM}" },
   {
    "name": "resource_appinsights",
    "label": "Application Insights",
    "query": {}
   },
   {
    "name": "resource_logs",
    "label": "Log Analytics workspace",
    "query": {}
   },
   {
    "name": "sub_appinsights",
    "label": "Sub AppInsights",
    "query": {}
   },
   {
    "name": "rg_appinsights",
    "label": "RG AppInsights",
    "query": {}
   },
   {
    "name": "sub_law",
    "label": "Sub Workspace",
    "query": {}
   },
   {
    "name": "rg_law",
    "label": "RG Workspace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Capacity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Capacity",
        "metricNamespace": "$ns_apim/$resource_apim",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "resources": [
         { "resourceGroup": "$rg", "resourceName": "" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Capacity",
        "metricNamespace": "$ns_apim/$resource_apim",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "resources": [
         { "resourceGroup": "$rg", "resourceName": "" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Requests (Failed & Successful)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "Success",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "GatewayResponseCode",
          "filters": [
           "0",
           "200"
          ],
          "operator": "eq"
         }
        ],
        "metricName": "Requests",
        "metricNamespace": "microsoft.apimanagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$rn",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "Fail",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "GatewayResponseCode",
          "filters": [
           "0",
           "200"
          ],
          "operator": "ne"
         }
        ],
        "metricName": "Requests",
        "metricNamespace": "microsoft.apimanagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$rn",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Duration of Backend Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BackendDuration",
        "metricNamespace": "microsoft.apimanagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$rn",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Requests by Response Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "GatewayResponseCode",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "Requests",
        "metricNamespace": "$ns_apim/$resource_apim",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
        "resources": [
         { "resourceGroup": "$rg", "resourceName": "" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "API, Operations, Requests (Log Analytics Enabled)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Calls by API",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ApiManagementGatewayLogs \r\n| where $__timeFilter(TimeGenerated)\r\n| where ApiId != \"\"\r\n| extend Success = iff(IsRequestSuccess==\"false\", 0, 1)\r\n| summarize RequestCount=count(CorrelationId), \r\n            AverageResponseTime=strcat(round(avg(TotalTime), 3), \" ms\"), \r\n            AverageResponseSize=strcat(round(avg(ResponseSize), 1), \" B\"),\r\n            SuccessRate=strcat(round(avg(Success)*100, 3), \"%\") by ApiId",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Calls by Operation",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ApiManagementGatewayLogs \r\n| where $__timeFilter(TimeGenerated)\r\n| where OperationId != \"\"\r\n| extend Success = iff(IsRequestSuccess==\"false\", 0, 1)\r\n| parse Url with * \"azure-api.net/\" UrlPath\r\n| extend Operation = UrlPath\r\n| summarize RequestCount=count(CorrelationId),\r\n            AverageResponseTime=strcat(round(avg(TotalTime), 3), \" ms\"), \r\n            AverageResponseSize=strcat(round(avg(ResponseSize), 1), \" B\"),\r\n            SuccessRate=strcat(round(avg(Success)*100, 3), \"%\") \r\n            by Operation //OperationId,\r\n               ",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ApiManagementGatewayLogs \r\n| where $__timeFilter(TimeGenerated)\r\n| where IsRequestSuccess == \"true\"\r\n| extend ServiceResponseTimeSec = tostring(round(BackendTime/1000.0,2))\r\n| extend ResponseTimeSec = tostring(round(TotalTime/1000.0,2))\r\n| project eSG=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'),\r\n          Method, URL=Url, ResponseCode, ServiceResponseCode=BackendResponseCode, \r\n          RequestSize=iff(RequestSize!=\"\", strcat(RequestSize, \" B\"), \"0 B\"),\r\n          ResponseSize=strcat(ResponseSize, \" B\"),\r\n          ResponseTimeSec, ServiceResponseTimeSec, Cache, IPAddress=CallerIpAddress\r\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "ApiManagementGatewayLogs \r\n| where $__timeFilter(TimeGenerated)\r\n| where IsRequestSuccess == \"false\"\r\n| extend ServiceResponseTimeSec = tostring(round(BackendTime/1000.0,2))\r\n| extend ResponseTimeSec = tostring(round(TotalTime/1000.0,2))\r\n| parse Url with * \"azure-api.net/\" UrlPath\r\n| extend Operation = UrlPath\r\n| project DateTimeSG=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore') , \r\n          Method, URL=Url, ResponseCode, ServiceResponseCode=BackendResponseCode, \r\n          RequestSize=iff(RequestSize!=\"\", strcat(RequestSize, \" B\"), \"0 B\"),\r\n          ResponseSize=strcat(ResponseSize, \" B\"),\r\n          ResponseTimeSec, ServiceResponseTimeSec, Cache, IPAddress=CallerIpAddress\r\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Health (App Insights Enabled)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 8, "x": 0, "y": 40 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 7, "x": 15, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Avg CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Avg Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "performanceCounters/memoryAvailableBytes",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Avg Server Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/rate",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Max Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Avg Dependency Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Dependency Call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Dependency Call Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Exception Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "performanceCounters/exceptionsPerSecond",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Server Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "southeastasia",
        "resourceGroup": "$rg_appinsights",
        "resourceName": "$resource_appinsights",
        "subscription": "$sub_appinsights"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub_appinsights"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Operations (App Insights Enabled)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 76 } },
  {
   "title": "Top 10 Failed Requests by Type",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| where Success == false\r\n| summarize failedCount=sum(ItemCount) by Name\r\n| top 10 by failedCount desc\r\n",
      "resources": [
       "/subscriptions/$sub_law/resourceGroups/$rg_law/providers/$ns_logs/$resource_logs"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Exceptions Causing Request Failures",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated) and Success == false\r\n| join kind= inner (\r\nAppExceptions\r\n| where $__timeFilter(TimeGenerated)\r\n) on OperationId\r\n| project ExceptionType = Type, FailedMethod = Method, RequestName = Name, RequestDuration = DurationMs",
      "resources": [
       "/subscriptions/$sub_law/resourceGroups/$rg_law/providers/$ns_logs/$resource_logs"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Operations via App Insights",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend AppInsights = split(_ResourceId, '/')[-1]\r\n| summarize\r\n RequestsCount=sum(ItemCount), \r\n AverageDurationMs=round(avg(DurationMs),2),\r\n  percentiles(DurationMs, 50, 95, 99) by OperationName, tostring(AppInsights)\r\n| order by RequestsCount desc",
      "resources": [
       "/subscriptions/$sub_law/resourceGroups/$rg_law/providers/$ns_logs/$resource_logs"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability Failures",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppAvailabilityResults \r\n| where $__timeFilter(TimeGenerated)\r\n| where Success == false\r\n| project TimeGenerated, Location, ClientType, ClientIP, ClientCity, ClientStateOrProvince, ClientCountryOrRegion",
      "resources": [
       "/subscriptions/$sub_law/resourceGroups/$rg_law/providers/$ns_logs/$resource_logs"
      ]
     },
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.OperationalInsights/workspaces/apimlab",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "apimlab" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}