{
 "title": "Level 2 / Firewall",
 "tags": [ "cwhd" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "fw",
    "label": "Firewall",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "SNAT Port Used %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SNATPortUtilization",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "region": "southeastasia",
        "resourceGroup": "$rg",
        "resourceName": "$fw",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "region": "southeastasia",
        "resourceGroup": "$rg",
        "resourceName": "$fw",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "App Rule Hits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ApplicationRuleHit",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "region": "southeastasia",
        "resourceGroup": "$rg",
        "resourceName": "$fw",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Network Rule Hits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NetworkRuleHit",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "region": "southeastasia",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "region": "southeastasia",
        "resourceGroup": "$rg",
        "resourceName": "$fw",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "### NAT Rule\r\n<hr style=\"height: 1px; background-color: #FFFFFF\">"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NAT Rule",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWNatRule \r\n| extend AzureFirewallIP = strcat(DestinationIp, ':', DestinationPort)\r\n| extend TranslatedIP = strcat(TranslatedIp, ':', TranslatedPort)\r\n| extend NatFlow = strcat('[incoming] ', SourceIp, ' -> [azfirewall] ', AzureFirewallIP, ' -> [translated]', TranslatedIp)\r\n| extend Rule = strcat(RuleCollection, '/', Rule)\r\n| where TimeGenerated >= $__timeFrom()\r\n| project\r\n    ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'),\r\n    ['NAT Flow']=NatFlow,\r\n    Rule",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "### Network Rule\r\n<hr style=\"height: 1px; background-color: #FFFFFF\">"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Denied Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWNetworkRule\r\n| extend Src = strcat(SourceIp, ':', SourcePort)\r\n| extend Dest = strcat(Protocol, '://', DestinationIp, ':', DestinationPort)\r\n| where Action == 'Deny'\r\n| where TimeGenerated >= $__timeFrom()\r\n| project ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'), Src, Dest, ActionReason",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Allowed Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWNetworkRule\r\n| extend Src = strcat(SourceIp, ':', SourcePort)\r\n| extend Dest = strcat(Protocol, '://', DestinationIp, ':', DestinationPort)\r\n| where Action != 'Deny'\r\n| where TimeGenerated >= $__timeFrom()\r\n| project ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'), Src, Dest, ActionReason",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "### App Rule\r\n<hr style=\"height: 1px; background-color: #FFFFFF\">"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Denied Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWApplicationRule\r\n| extend dest = strcat(tolower(Protocol), '://', Fqdn, ':', DestinationPort)\r\n| extend rule = strcat(RuleCollection, '/', Rule)\r\n| where Action != 'Allow'\r\n| where TimeGenerated >= $__timeFrom()\r\n| project \r\n  ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'), \r\n  ['Source']=strcat(SourceIp,':',SourcePort), \r\n  ['Destination']=dest, ['Deny Reason']=ActionReason",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Allowed Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 41 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWApplicationRule\r\n| extend dest = strcat(tolower(Protocol), '://', Fqdn, ':', DestinationPort)\r\n| extend rule = strcat(RuleCollection, '/', Rule)\r\n| where TimeGenerated >= $__timeFrom()\r\n| project \r\n  ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'),\r\n  ['Source']=strcat(SourceIp,':',SourcePort), \r\n  ['Destination']=dest, \r\n  ['Firewall Rule']=rule",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "### DNS Proxy\r\n<hr style=\"height: 1px; background-color: #FFFFFF\">"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "DNS Query with Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 51 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWDnsQuery\r\n| extend src = strcat(SourceIp, ':', SourcePort)\r\n| where ErrorNumber != 0\r\n| where TimeGenerated >= $__timeFrom()\r\n| project ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'), ['Source']=src, QueryType, QueryName, RequestDurationSecs",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "DNS Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 59 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AZFWDnsQuery\r\n| extend src = strcat(SourceIp, ':', SourcePort)\r\n| where ErrorNumber == 0\r\n| where TimeGenerated >= $__timeFrom()\r\n| project ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'),['Source']=src, QueryType, QueryName, RequestDurationSecs",
      "resources": [
       "/subscriptions/${sub}/resourceGroups/${rg}/providers/Microsoft.Network/azureFirewalls/${fw}"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}