{
 "title": "Level 2 / Key Vaults",
 "description": "The dashboard provides insights of Azure Key Vaults overview, failures and operations.",
 "tags": [
  "azure-monitor-plugin",
  "cwhd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "sub", "label": "Subscription", "query": "subscriptions()" },
   { "name": "rg", "label": "Resource Group", "query": "ResourceGroups($sub)" },
   { "name": "ns", "label": "Namespace", "query": "${VAR_NS}" },
   { "name": "resource", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   { "name": "ws", "label": "Workspace", "query": "Workspaces($sub)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service API Hits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiHit",
      "metricNamespace": "microsoft.keyvault/vaults",
      "resources": [
       { "metricNamespace": "Microsoft.KeyVault/vaults", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Service API Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiLatency",
      "metricNamespace": "microsoft.keyvault/vaults",
      "resources": [
       { "metricNamespace": "Microsoft.KeyVault/vaults", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttling (429)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Successes (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCodeClass", "filters": [ "2xx" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failures (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCodeClass", "filters": [ "4xx" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Authentication Errors (401 & 403)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "401" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "403" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Activity Type", "value": "ActivityType" },
       { "text": "Activity Name", "value": "ActivityName" },
       { "text": "Status Code", "value": "StatusCode" },
       { "text": "Status Code Class", "value": "StatusCodeClass" }
      ],
      "metricDefinition": "Microsoft.KeyVault/vaults",
      "metricName": "ServiceApiResult",
      "metricNamespace": "Microsoft.KeyVault/vaults",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let rawData = AzureDiagnostics \r\n    // Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n    | where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n    | where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r\n    // Create ResultStatus with all the 'success' results bucked as 'Success'\r\n    // Certain operations like StorageAccountAutoSyncKey have no ResultSignature, for now set to 'Success' as well\r\n    | extend ResultStatus = case (ResultSignature == \"\", \"Success\",\r\n        ResultSignature == \"OK\", \"Success\",\r\n        ResultSignature == \"Accepted\", \"Success\",\r\n        ResultSignature);                            \r\nrawData \r\n| make-series Trend = count() default = 0 on TimeGenerated from ago(1d) to now() step 30m by ResultStatus\r\n| join kind = inner (rawData\r\n    | where $__timeFilter(TimeGenerated)\r\n    | summarize Count = count() by ResultStatus\r\n    )\r\n    on ResultStatus\r\n    \r\n\r\n| project ResultStatus, Count, Trend\r\n| order by Count desc;\r\n",
      "resources": [ "$ws" ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Success Operations Counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let rawData = AzureDiagnostics \r\n    // Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n    | where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n    | where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r\n    // Create ResultStatus with all the 'success' results bucked as 'Success'\r\n    // Certain operations like StorageAccountAutoSyncKey have no ResultSignature, for now set to 'Success' as well\r\n    | extend ResultStatus = case (ResultSignature == \"\", \"Success\",\r\n        ResultSignature == \"OK\", \"Success\",\r\n        ResultSignature == \"Accepted\", \"Success\",\r\n        ResultSignature);                            \r\nrawData\n| where $__timeFilter(TimeGenerated)\n| extend resultCount = iif(ResultStatus == \"Success\", 1, 0)\n| summarize count(resultCount) by bin(TimeGenerated, 30m)\n| sort by TimeGenerated;\n\r\r\n\r",
      "resources": [ "$ws" ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "All Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let rawData = AzureDiagnostics \r\n    // Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n    | where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n    | where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r;                     \r\nrawData \r\n| make-series Trend = count() default = 0 on TimeGenerated from ago(1d) to now() step 30m by ResultSignature \n| join kind = inner (rawData\n    | where $__timeFilter(TimeGenerated)\r\n    | summarize Count = count() by ResultSignature \n    )\r\n    on ResultSignature \n\r\n\r\n| project ResultSignature , Count, Trend\r\n| order by Count desc;",
      "resources": [ "$ws" ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "All Operations Counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let rawData = AzureDiagnostics \r\n    // Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n    | where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n    | where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r;                          \r\nrawData\n| where $__timeFilter(TimeGenerated)\n| summarize count(ResultSignature ) by bin(TimeGenerated, 30m)\n| sort by TimeGenerated;\n\r\r\n\r",
      "resources": [ "$ws" ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Operations by Name",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let data = AzureDiagnostics \r\n    | where TimeGenerated > ago(1d)\r\n    // Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n    | where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n    | where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r\n    // Create ResultStatus with all the 'success' results bucked as 'Success'\r\n    // Certain operations like StorageAccountAutoSyncKey have no ResultSignature, for now set to 'Success' as well\r\n    | extend ResultStatus = case (ResultSignature == \"\", \"Success\",\r\n        ResultSignature == \"OK\", \"Success\",\r\n        ResultSignature == \"Accepted\", \"Success\",\r\n        ResultSignature)\r\n    | where ResultStatus == 'All' or 'All' == 'All';\r\ndata\r\n// Data aggregated to the OperationName\r\n| summarize OperationCount = count(), SuccessCount = countif(ResultStatus == \"Success\"), FailureCount = countif(ResultStatus != \"Success\"), PDurationMs = percentile(DurationMs, 99) by Resource, OperationName\r\n| join kind=inner (data\r\n    | make-series Trend = count() default = 0 on TimeGenerated from ago(1d) to now() step 30m by OperationName\r\n    | project-away TimeGenerated)\r\n    on OperationName\r\n| order by OperationCount desc\r\n| project \r\nName = strcat('⚡', OperationName), \r\nId = strcat(Resource, '/', OperationName), \r\n['Operation count'] = OperationCount, \r\n//['Operation count trend'] = Trend, \r\n['Success count'] = SuccessCount, \r\n['Failure count'] = FailureCount, \r\n['p99 Duration'] = PDurationMs",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Operations by Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let gridRowSelected = dynamic({\"Id\": \"*\"});\r\nlet resourceName = split(gridRowSelected.Id, \"/\")[0];\r\nlet operationName = split(gridRowSelected.Id, \"/\")[1];\r\nAzureDiagnostics\r\n| where TimeGenerated >= $__timeFrom() \r\n//| where TimeGenerated > ago(1d)\r\n// Ignore Authentication operations with a 401. This is normal when using Key Vault SDK, first an unauthenticated request is done then the response is used for authentication.\r\n| where Category == \"AuditEvent\" and not (OperationName == \"Authentication\" and httpStatusCode_d == 401)\r\n| where OperationName in ('SecretGet', 'VaultGet') or '*' in ('SecretGet', 'VaultGet')\r\n| where resourceName == \"*\" or Resource == resourceName\r\n| where operationName == \"\" or OperationName == operationName\r\n// Create ResultStatus with all the 'success' results bucked as 'Success'\r\n// Certain operations like StorageAccountAutoSyncKey have no ResultSignature, for now set to 'Success' as well\r\n| extend ResultStatus = case (ResultSignature == \"\", \"Success\",\r\n    ResultSignature == \"OK\", \"Success\",\r\n    ResultSignature == \"Accepted\", \"Success\",\r\n    ResultSignature)\r\n| where ResultStatus == 'All' or 'All' == 'All'\r\n| extend p = pack_all()\r\n| mv-apply p on \r\n    ( \r\n    extend key = tostring(bag_keys(p)[0])\r\n    | where isnotempty(p[key]) and isnotnull(p[key])\r\n    | where key !in (\"SourceSystem\", \"Type\")\r\n    | summarize make_bag(p)\r\n    )\r\n| project \r\n    ['DateTime SG']=datetime_utc_to_local(TimeGenerated, 'Asia/Singapore'),\r\n    //Time=TimeGenerated, \r\n    Operation=OperationName, \r\n    Result=ResultSignature,\r\n    Duration = DurationMs, \r\n    [\"Details\"]=bag_p\r\n| sort by ['DateTime SG'] desc\r\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}