name: Build Windows Docker Image

on:
  push:
    branches: [ feat/wara ]
  pull_request:
    branches: [ feat/wara ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # github actions pip freeze
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - run: pip freeze > requirements.txt


      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: runner.os != 'Linux'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platform: windows/amd64
          push: true
          tags:  ${{ vars.DOCKER_IMAGE_TAG }}

