name: Build Windows Docker Image

on:
  push:
    branches: [ feat/wara ]
  pull_request:
    branches: [ feat/wara ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # github actions pip freeze
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - run: pip freeze > requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker build
        shell: powershell
        run: |
          docker build . -t docker.io/wxzd/cwhd:v0.1.1-wara


      - name: Docker push
        shell: powershell
        run: |
          docker push docker.io/wxzd/cwhd:v0.1.1-wara
